services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Usa 'root' según tu .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}           # 'Super_heores' (ojo el typo)
      MYSQL_USER: ${MYSQL_USER}                   # 'user'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}           # 'password'
      MYSQL_GRANT: "ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%'"  # ¡Nueva línea!
      MYSQL_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_game:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"                      # Puerto 3306
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db                                # Debe ser 'db' (nombre del servicio)
      PMA_USER: root                     # 'user'
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}             # 'password'
    ports:
      - "8080:80"
    networks:
      - backend

  fastapi:
    build: ./app
    environment:
      API_HOST: ${API_HOST}                       # '0.0.0.0'
      API_PORT: ${API_PORT}                       # '8000'
    ports:
      - "${API_PORT}:${API_PORT}"                 # Mapea el puerto 8000
    depends_on:
      - db
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge